### PR TITLE
SCRIPT1028: Expected identifier, string or number

### PR DESCRIPTION
**Pull request by sagar1992**

### CODE REVIEW

**Comment by rwjblue** [comment]
I vaguely recall that trailing commas is only an issue in IE8, is that the browser you received the error in?

**Comment by sagar1992** [comment]
Yes.

**Comment by Turbo87** [comment]
@rwjblue is there no Babel transformation that takes care of such things?

**Comment by rwjblue** [comment]
There may be, but we don't run Babel on this repo (it's still a bower dep).

**Comment by Turbo87** [comment]
I see, thanks

**Pull request merged**
