### PR TITLE
Export modules with RSVP to avoid destructuring

### PR DESCRIPTION
**Pull request by danmcclain**

### CODE REVIEW

**Comment by rwjblue** [comment]
I like it. I'd much prefer to import named instead of importing RSVP then destructuring. I believe this also matches RAVP's normal exports. 

@danmcclain - We will need to PR against Stef's pending PR in Ember itself (we need to keep these repos in sync). Would you mind doing that also?


@stefanpenner - r?

**Comment by stefanpenner** [comment]
I would prefer to wait as we decide what we want to expose. Wholesale including all the things, like `cast` and `throw` seems like a bad choice, maybe others.

**Comment by rwjblue** [comment]
@stefanpenner - Sounds good. I believe the point here was to emulate the already existing RSVP public API (taken from [lib/rsvp.js](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp.js#L50-L70)).

**Comment by danmcclain** [comment]
@rwjblue Confirm, I was going for 1:1 with the current `rsvp.js` exports

**Comment by rwjblue** [comment]
@stefanpenner - Are those that you mentioned going to be deprecated and removed by RSVP?  Either way, can you list the ones to remove from this PR so that we can at least use imports for some of the things?

**Comment by Turbo87** [comment]
closing due to inactivity

**Pull request closed without merging**
