### PR TITLE
Added shims for getOwner and setOwner

### PR DESCRIPTION
**Pull request by martndemus**
Not sure if the module naming is correct? Should both methods go into the same module?

### CODE REVIEW

**Comment by rwjblue** [comment]
Let me check with the team about what we want the module paths to be...

**Comment by martndemus** [comment]
@rwjblue any update?

**Comment by danmcclain** [comment]
Any movement on this @rwjblue?

**Comment by onlymejosh** [comment]
Any updates on this @rwjblue I see there is a failing build but it looks like travis has been removed from this project now?

**Comment by rwjblue** [comment]
I'd say lets go with:

    import get from 'ember-owner/get';
    import set from 'ember-owner/set';

We will also need to PR against the open PR in ember moving these shims upstream...

**Comment by cibernox** [comment]
@martndemus If you're busy I have some cycles to add this.

**Comment by martndemus** [comment]
@cibernox Be my guest!

**Pull request closed without merging**
