### PR TITLE
Add `ember-testing` import path, with `isTesting` and `setTesting` named exports

### PR DESCRIPTION
**Pull request by cibernox**
I got to be a little creative here 😁 

This follows an informal conversation in slack, so maybe it's not the right path.

### CODE REVIEW

**Comment by rwjblue** [comment]
Only canary is using a descriptor here, I think for this repo we should do something simpler:

```js
define('ember-testing', [], function() {
  'use strict';
 
  return {
    isTesting: function() {
      return Ember.testing;
    },
    setTesting: function(value) {
      Ember.testing = value;
    }
  };
});
```

**Comment by cibernox** [comment]
Good point. I'll do that

**Comment by cibernox** [comment]
Done and tried in a 2.5 app. `isTesting()` returns `undefined` when not in testing, not `false`, but `Ember.testing` behaves the same way, so although unexpected, it is consistent.

**Comment by rwjblue** [comment]
👍 from me (we will also need another PR against the Ember PR).

@krisselden / @stefanpenner - Thoughts?

**Comment by cibernox** [comment]
The version in ember must be identical or should extract the functions from the descriptor?

**Comment by rwjblue** [comment]
@cibernox - I am not 100% sure, but the descriptor approach seems better to me (since it mirrors the internal functions nicely).

**Comment by cibernox** [comment]
Done in ember too

**Comment by stefanpenner** [comment]
@krisselden r?

**Comment by cibernox** [comment]
Any update on this?

**Comment by cibernox** [comment]
Ping

**Comment by stefanpenner** [comment]
@cibernox i believe this repo is frozen until the public module API for ember itself is defined.

**Comment by rwjblue** [comment]
There have been recent developments around this. I believe that @tomdale will be picking up the torch sometime after fastboot 1.0 is shipped.

**Comment by stefanpenner** [comment]
@rwjblue sweet

**Comment by Turbo87** [comment]
@rwjblue @tomdale @cibernox any updates on this?

**Comment by Turbo87** [comment]
closing due to inactivity and deprecation of the addon

**Pull request closed without merging**
