### PR TITLE
Implement new module shims

### PR DESCRIPTION
**Pull request by martndemus**
@locks asked me to PR this.

### CODE REVIEW

**Comment by stefanpenner** [comment]
should these be implemented in the ember-source addon itself?

**Comment by workmanw** [comment]
@martndemus Can you add a shim for `Ember.String.isHTMLSafe`? I have a PR to add it to the "classic shims". I'm assuming this will supercede my open PR if it is to land here. Just wanted to make sure that was covered because not having a shim for `isHTMLSafe` is currently blocking another PR of mine. :)

**Comment by martndemus** [comment]
@rwjblue / @locks updated!

Notes:
- Haven't added `isHTMLSafe` to the new imports as it isn't in the RFCs list. I'll add it if I get a blessing from a Ember god to do so.
- Haven't deprecated the Ember.Test shims, as they don't have an analog in the new shims yet.

**Comment by workmanw** [comment]
@martndemus @rwjblue Hmm ... you're right `isHTMLSafe` is not in the RFC, but it's counterpart `htmlSafe` is. I think part of the problem is that `isHTMLSafe` landed in the release channel around the same time the RFC was first drafted and it just got missed for that reason.

I'm not sure what the procedure here is. The RFC has already been merged, but clearly `isHTMLSafe` is public API. Do we need to try to get the RFC amended to include this?

**Comment by msalahz** [comment]
Any updates about this  ?

**Comment by Turbo87** [comment]
would it be possible for the deprecation messages to explicitly mention the new path so that you don't have to look it up manually all the time?

**Comment by rwjblue** [comment]
Yeah, that does sound nice. We should also probably also have the deprecation link back to a section on the README here so that we can provide more "prosey" explanations...

**Comment by locks** [comment]
I mentioned on Slack that we also have an automatic migration tool, which might be preferable to adding that logic here as well. 
My Kingdom for a clickable link that calls the migrator :joy:

**Comment by Turbo87** [comment]
Merged as discussed in the Ember CLI team meeting yesterday. We will release this as a beta today and then continue from there.

**Comment by martndemus** [comment]
🎉

**Pull request merged**
