### PR TITLE
Add K as a `ember-utils`

### PR DESCRIPTION
**Pull request by duggiefresh**

### CODE REVIEW

**Comment by leizhao4** [comment]
Is this going to be merged (or why it shouldn't)?

**Comment by stefanpenner** [comment]
`Ember.K` is from another era. It is the K combinator, and really isn't used any longer.

in nearly all cases:

```
someHook: Ember.K,

// is nicely replaced by:
someHook() { }

// or if the hook must be chainable

someHook() { return this; }
```

**Comment by stefanpenner** [comment]
Ah, it is also worth noting. Shims are more or less frozen until the ES6 Module API is selected for ember.

**Comment by leizhao4** [comment]
@stefanpenner I see. Thanks for your explanation!

**Pull request closed without merging**
